version: '3.8'

services:
    transformers-inference:
        ports:
            - 8000:8080
        container_name: embedding-model
        image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1

    weaviate:
        image: semitechnologies/weaviate:1.29.1
        ports:
            - 8080:8080
        restart: on-failure:0
        container_name: weaviate-db
        environment:
            QUERY_DEFAULTS_LIMIT: 25
            AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
            PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
            DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
            ENABLE_MODULES: 'text2vec-transformers'
            TRANSFORMERS_INFERENCE_API: 'http://46.202.162.249:8080'
        volumes:
            - weaviate_data:/var/lib/weaviate
        depends_on:
            - transformers-inference

volumes:
    weaviate_data:
        driver: local